export const BRAND_SECTORS = {
  'siwa-stay': {
    category: 'accommodation',
    sectionId: 'sec_3_facilities',
    label: 'Siwa Stay',
    title: 'Find your stay in Siwa Oasis',
    description: 'Explore hotels, eco-lodges, camps, retreats, and accommodation offers from Siwify and local providers.',
    accent: '#287a55',
  },
  'siwa-table': {
    category: 'food',
    sectionId: 'sec_4_gastronomy',
    label: 'Siwa Table',
    title: 'Taste Siwa Oasis',
    description: 'Find restaurants, cafes, kitchens, local food experiences, and dining offers across Siwa.',
    accent: '#b4533c',
  },
  'siwa-experiences': {
    category: 'adventure',
    sectionId: 'sec_5_experiences',
    label: 'Siwa Experiences',
    title: 'Explore Siwa Oasis',
    description: 'Discover tours, journeys, activities, guides, and packages, with their participating service providers.',
    accent: '#287a55',
  },
  'siwa-retreat': {
    category: 'wellness',
    sectionId: 'sec_9_marketplace_catalog',
    label: 'Siwa Retreat',
    title: 'Rest and restore in Siwa',
    description: 'Explore wellness stays, salt lakes, hot springs, sand baths, spas, and restorative retreats.',
    accent: '#58765a',
  },
  'siwa-move': {
    category: 'logistics',
    sectionId: 'sec_6_guardian',
    label: 'Siwa Move',
    title: 'Move around Siwa with ease',
    description: 'Find transfers, tuk-tuks, 4x4 transport, rentals, and mobility offers from local providers.',
    accent: '#a15d2b',
  },
  'siwa-craft': {
    category: 'crafts',
    sectionId: 'sec_9_marketplace_catalog',
    label: 'Siwa Craft',
    title: 'Discover craft and makers in Siwa',
    description: 'Explore handmade goods, workshops, artisan businesses, and local product offers.',
    accent: '#9b6832',
  },
  'siwa-grown-produced': {
    category: 'agriculture_industry',
    sectionId: 'sec_9_marketplace_catalog',
    label: 'Siwa Grown & Produced',
    title: 'Explore what Siwa grows and makes',
    description: 'Connect with farms, date and olive producers, food processors, factories, and trade suppliers.',
    accent: '#477448',
  },
  'siwa-invest': {
    category: 'investment_parent',
    sectionId: 'sec_7_investment',
    label: 'Siwa Invest',
    title: 'Invest in Siwa Oasis',
    description: 'Explore approved investments and partnerships from Siwify and businesses across Siwa.',
    accent: '#98713a',
  },
  'siwa-services': {
    category: 'services_professional',
    sectionId: 'sec_6_guardian',
    label: 'Siwa Services',
    title: 'Find services across Siwa businesses',
    description: 'Discover local operators and professional providers supporting stays, dining, journeys, transport, and trade.',
    accent: '#64776b',
  },
} as const;

export type BrandSectorSlug = keyof typeof BRAND_SECTORS;

export const BRAND_ROUTE_BY_TYPE: Record<string, string> = {
  accommodation: 'siwa-stay',
  hotel: 'siwa-stay',
  camps: 'siwa-stay',
  lodge: 'siwa-stay',
  food: 'siwa-table',
  restaurant: 'siwa-table',
  cafe: 'siwa-table',
  adventure: 'siwa-experiences',
  activities: 'siwa-experiences',
  tours: 'siwa-experiences',
  journeys: 'siwa-experiences',
  arts_culture: 'siwa-experiences',
  events_entertainment: 'siwa-experiences',
  wellness: 'siwa-retreat',
  logistics: 'siwa-move',
  transportation: 'siwa-move',
  crafts: 'siwa-craft',
  agriculture_industry: 'siwa-grown-produced',
  production_trade: 'siwa-grown-produced',
  investment_parent: 'siwa-invest',
  services_professional: 'siwa-services',
  education_research: 'siwa-services',
  media_content: 'siwa-services',
};