-- Canonical service records shared by minisites, search, marketplace,
-- packages, and customer request workflows.
CREATE TABLE IF NOT EXISTS vendor_services (
  id VARCHAR(36) PRIMARY KEY,
  business_id VARCHAR(36) NOT NULL,
  vendor_id VARCHAR(36) NULL,
  source_component_id VARCHAR(36) NULL,
  source_component_data_id VARCHAR(36) NULL,
  category VARCHAR(80) NOT NULL,
  service_type VARCHAR(120) NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  attributes JSON NULL,
  price DECIMAL(12,2) NULL,
  currency VARCHAR(10) DEFAULT 'EGP',
  price_unit VARCHAR(40) NULL,
  capacity VARCHAR(120) NULL,
  availability VARCHAR(255) NULL,
  valid_from DATE NULL,
  valid_until DATE NULL,
  approval_status ENUM('draft','pending_approval','published','rejected','suspended') NOT NULL DEFAULT 'pending_approval',
  audience_scopes JSON NOT NULL,
  placements JSON NOT NULL,
  booking_mode ENUM('request','book','contact') NOT NULL DEFAULT 'request',
  package_eligible BOOLEAN NOT NULL DEFAULT FALSE,
  approved_by VARCHAR(36) NULL,
  approved_at DATETIME NULL,
  rejection_note TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_vendor_service_source (source_component_data_id),
  INDEX idx_vendor_services_component (business_id, source_component_id),
  INDEX idx_vendor_services_business (business_id),
  INDEX idx_vendor_services_category (category),
  INDEX idx_vendor_services_status (approval_status),
  INDEX idx_vendor_services_dates (valid_from, valid_until),
  CONSTRAINT fk_vendor_services_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;