#!/usr/bin/env node

/**
 * ═══════════════════════════════════════════════════════════════════════
 *  SIWIFY / SIWA OASIS — UNIVERSAL DISASTER RECOVERY & BOOTSTRAPPER
 *  Works seamlessly on Windows, Linux, and macOS.
 * ═══════════════════════════════════════════════════════════════════════
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const rootDir = path.resolve(__dirname, '..');
const configPath = path.join(__dirname, 'env.backup.json');

console.log('\n======================================================');
console.log('   🚀 SIWIFY.COM — UNIVERSAL ENVIRONMENT BOOTSTRAPPER');
console.log('======================================================\n');

if (!fs.existsSync(configPath)) {
  console.error('❌ Configuration file not found at:', configPath);
  process.exit(1);
}

const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));

// 1. Generate .env.local
const envLocalContent = `# Auto-generated by RESCUE_KIT on ${new Date().toISOString()}
DB_HOST=${config.database.DB_HOST}
DB_PORT=${config.database.DB_PORT}
DB_USER=${config.database.DB_USER}
DB_PASSWORD=${config.database.DB_PASSWORD}
DB_NAME=${config.database.DB_NAME}
DB_SSL=${config.database.DB_SSL}
DB_FALLBACK_TO_PROD=${config.database.DB_FALLBACK_TO_PROD}

JWT_SECRET=${config.auth.JWT_SECRET}
SESSION_COOKIE_NAME=${config.auth.SESSION_COOKIE_NAME}

NEXT_PUBLIC_APP_URL=${config.app.NEXT_PUBLIC_APP_URL_DEV}
NODE_ENV=development

CLOUDINARY_CLOUD_NAME=${config.cloudinary.CLOUDINARY_CLOUD_NAME}
CLOUDINARY_API_KEY=${config.cloudinary.CLOUDINARY_API_KEY}
CLOUDINARY_API_SECRET=${config.cloudinary.CLOUDINARY_API_SECRET}
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${config.cloudinary.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
`;

const envLocalPath = path.join(rootDir, '.env.local');
fs.writeFileSync(envLocalPath, envLocalContent, 'utf8');
console.log('✅ Generated .env.local with TiDB & Cloudinary credentials');

// 2. Generate .env.production
const envProdContent = `# Auto-generated Production Config on ${new Date().toISOString()}
DB_HOST=${config.database.DB_HOST}
DB_PORT=${config.database.DB_PORT}
DB_USER=${config.database.DB_USER}
DB_PASSWORD=${config.database.DB_PASSWORD}
DB_NAME=${config.database.DB_NAME}
DB_SSL=${config.database.DB_SSL}

JWT_SECRET=${config.auth.JWT_SECRET}
SESSION_COOKIE_NAME=${config.auth.SESSION_COOKIE_NAME}

NEXT_PUBLIC_APP_URL=${config.app.NEXT_PUBLIC_APP_URL_PROD}
NODE_ENV=production

CLOUDINARY_CLOUD_NAME=${config.cloudinary.CLOUDINARY_CLOUD_NAME}
CLOUDINARY_API_KEY=${config.cloudinary.CLOUDINARY_API_KEY}
CLOUDINARY_API_SECRET=${config.cloudinary.CLOUDINARY_API_SECRET}
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${config.cloudinary.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
`;

const envProdPath = path.join(rootDir, '.env.production');
fs.writeFileSync(envProdPath, envProdContent, 'utf8');
console.log('✅ Generated .env.production');

// 3. Configure .vercel/repo.json
const vercelDir = path.join(rootDir, '.vercel');
if (!fs.existsSync(vercelDir)) {
  fs.mkdirSync(vercelDir, { recursive: true });
}
const repoJson = {
  remoteName: 'origin',
  projects: [
    {
      id: config.vercel.project_id,
      name: config.vercel.project_name,
      directory: '.',
      orgId: config.vercel.org_id
    }
  ]
};
fs.writeFileSync(path.join(vercelDir, 'repo.json'), JSON.stringify(repoJson, null, 2), 'utf8');
console.log('✅ Configured .vercel project linkage');

// 4. Check / Configure Git
try {
  const isGit = fs.existsSync(path.join(rootDir, '.git'));
  if (!isGit) {
    console.log('ℹ️  Initializing fresh Git repository...');
    execSync('git init', { cwd: rootDir, stdio: 'inherit' });
    execSync(`git remote add origin ${config.github.repository_url}`, { cwd: rootDir, stdio: 'inherit' });
    execSync('git branch -M main', { cwd: rootDir, stdio: 'inherit' });
    console.log('✅ Git repository connected to GitHub origin');
  } else {
    try {
      execSync(`git remote set-url origin ${config.github.repository_url}`, { cwd: rootDir, stdio: 'ignore' });
    } catch {
      execSync(`git remote add origin ${config.github.repository_url}`, { cwd: rootDir, stdio: 'ignore' });
    }
    console.log('✅ GitHub remote origin verified');
  }
} catch (err) {
  console.warn('⚠️  Git configuration warning:', err.message);
}

// 5. Test Database Connection
console.log('\n📡 Testing Master Database Connection (TiDB Cloud)...');
try {
  const mysql = require('mysql2/promise');
  async function testDB() {
    const conn = await mysql.createConnection({
      host: config.database.DB_HOST,
      port: parseInt(config.database.DB_PORT),
      user: config.database.DB_USER,
      password: config.database.DB_PASSWORD,
      database: config.database.DB_NAME,
      ssl: { rejectUnauthorized: false }
    });
    const [rows] = await conn.query('SELECT COUNT(*) as total_tables FROM information_schema.tables WHERE table_schema = ?', [config.database.DB_NAME]);
    console.log(`✅ Master Database CONNECTED! (Found ${rows[0].total_tables} tables in schema)`);
    await conn.end();
  }
  testDB().catch(e => console.error('⚠️ Database test query error:', e.message));
} catch (e) {
  console.log('ℹ️  (mysql2 module will be tested once npm install runs)');
}

console.log('\n======================================================');
console.log('🎉 RESCUE & RESTORATION COMPLETED SUCCESSFULLY!');
console.log('======================================================');
console.log('👉 Next Steps:');
console.log('   1. Install dependencies: npm install');
console.log('   2. Start local server:   npm run dev');
console.log('   3. Deploy to production: npm run live:once');
console.log('======================================================\n');
